# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2
workflows:
  build:
    jobs:
      - filters:
          branches:
            only: master

      docker:
        - image: circleci/node:10-browsers

      working_directory: ~/repo
  
      steps:
        - checkout
  
        # Download and cache dependencies
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-
  
        - run: npm install
        - run: node node_modules/protractor/bin/webdriver-manager update

        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}
  
        # run tests!
        - run: npm run lint
        - run: npm run e2e

        # build!
        - run: npm run build --prod
